# Generated by Django 3.2.3 on 2021-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokeclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_name', models.TextField()),
                ('poke_type', models.TextField()),
                ('height', models.FloatField()),
                ('moves', models.TextField()),
                ('totabilities', models.IntegerField()),
            ],
        ),
    ]
