# Generated by Django 3.2.3 on 2021-07-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokeclass',
            old_name='height',
            new_name='weight',
        ),
    ]
