# Generated by Django 3.2.3 on 2021-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_rename_pokeclass_poke_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke_class',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='poke_class',
            name='totabilities',
        ),
        migrations.AddField(
            model_name='poke_class',
            name='totmoves',
            field=models.IntegerField(default=0),
        ),
    ]
