# Generated by Django 3.2.3 on 2021-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20210730_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke_class',
            name='backpic',
            field=models.ImageField(default='https://safetyaustraliagroup.com.au/wp-content/uploads/2019/05/image-not-found.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='poke_class',
            name='frontpic',
            field=models.ImageField(default='https://safetyaustraliagroup.com.au/wp-content/uploads/2019/05/image-not-found.png', upload_to=''),
        ),
    ]
