# Generated by Django 3.2.3 on 2021-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20210730_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke_class',
            name='backpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='poke_class',
            name='frontpic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
