# Generated by Django 3.2.3 on 2021-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_auto_20210730_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke_class',
            old_name='backpic',
            new_name='image_file',
        ),
        migrations.RemoveField(
            model_name='poke_class',
            name='frontpic',
        ),
        migrations.AddField(
            model_name='poke_class',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
