# Generated by Django 3.2.3 on 2021-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20210730_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke_class',
            name='type',
            field=models.TextField(default='type_1'),
        ),
    ]
