# Generated by Django 3.2.3 on 2021-07-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_poke_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke_class',
            name='type',
        ),
        migrations.AddField(
            model_name='poke_class',
            name='no_poke',
            field=models.IntegerField(default=1),
        ),
    ]
